In [12]:
import tensorflow as tp



In [2]:
cons=tp.constant("Hello")
cons

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello'>

In [3]:
tp.print(cons)


Hello


In [4]:
print(tp.__version__)


2.7.0


In [5]:
a=tp.constant(3.0)
b=tp.constant(4.0)
c=a+b
print([c,a,b])
tp.print([c,a,b])

[<tf.Tensor: shape=(), dtype=float32, numpy=7.0>, <tf.Tensor: shape=(), dtype=float32, numpy=3.0>, <tf.Tensor: shape=(), dtype=float32, numpy=4.0>]
[7, 3, 4]


In [13]:
a=tp.placeholder(tp.float32)
b=tp.placeholder(tp.float32)
adder=a+b
tp.print(adder,feed_dict={a:[1,7,6],b:[3,4,6]})

AttributeError: module 'tensorflow' has no attribute 'placeholder'